# Generated by Django 5.2.16 on 2026-07-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencehistory',
            name='task',
            field=models.CharField(choices=[('sentiment', 'Sentiment'), ('summarize', 'Summarize'), ('moderate', 'Moderate')], max_length=20),
        ),
    ]
