# Generated by Django 6.0.6 on 2026-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
    ]
